
platform: android
appium:
  url: http://127.0.0.1:4723/

android:
  device_name: Pixel_XL
  platform_version: "16"
  app_path: /path/to/your/.apk
  app_activity: com.MainActivity
  app_package: com.dev
  no_reset: false
  new_command_timeout: 100
  dont_stop_app_on_reset: false
  unicode_keyboard: true
  adb_exec_timeout_ms: 40000
  auto_grant_permissions: true
  auto_launch: true

reporting:
  allure_dir: artifacts/allure

capabilities:
  raw:
    appium:newCommandTimeout: 120
